__include__: ['../visdrone_pico.yml']
experiment_name: M0_visual
output_dir: ./outputs/M0_visual
DEIMTransformer:
  use_water_quality: False
  water_features: []
  water_self_attn: False
  query_water_cross_attn: False
  learnable_gate: False
