__include__: ['../visdrone_pico.yml']
experiment_name: V2_T_DO_pH
output_dir: ./outputs/V2_T_DO_pH
DEIMTransformer:
  use_water_quality: True
  water_features: [temperature, do, ph]
  water_self_attn: True
  query_water_cross_attn: True
  learnable_gate: True
