__include__: ['../visdrone_pico.yml']
experiment_name: V4_T_pH
output_dir: ./outputs/V4_T_pH
DEIMTransformer:
  use_water_quality: True
  water_features: [temperature, ph]
  water_self_attn: True
  query_water_cross_attn: True
  learnable_gate: True
