__include__: ['../visdrone_pico.yml']
experiment_name: V6_DO
output_dir: ./outputs/V6_DO
DEIMTransformer:
  use_water_quality: True
  water_features: [do]
  water_self_attn: True
  query_water_cross_attn: True
  learnable_gate: True
