task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 12
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:\Users\ERT ECT\Desktop\archive (1)\train
    ann_file: C:\Users\ERT ECT\Desktop\archive (1)\annotations_VisDrone_train.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: [4, 64, 120]
        ops: ['Mosaic', 'RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
      mosaic_prob: 0.5
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 640
    base_size_repeat: 20
    stop_epoch: 120
    ema_restart_decay: 0.9999
    mixup_prob: 0.5
    mixup_epochs: [4, 64]

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:\Users\ERT ECT\Desktop\archive (1)\val
    ann_file: C:\Users\ERT ECT\Desktop\archive (1)\annotations_VisDrone_val.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction