task: detection
evaluator:
  type: CocoEvaluator
  iou_types:
  - bbox
num_classes: 2
remap_mscoco_category: false
train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:\Users\l\Desktop\fish_dataset622\train
    ann_file: C:\Users\l\Desktop\fish_dataset622\train\coco_detection_train0.json
    return_masks: false
    transforms:
      type: Compose
      ops:
      - type: RandomPhotometricDistort
        p: 0.5
      - type: RandomZoomOut
        fill: 0
      - type: RandomIoUCrop
        p: 0.8
      - type: SanitizeBoundingBoxes
        min_size: 1
      - type: RandomHorizontalFlip
      - type: Resize
        size:
        - 640
        - 640
      - type: SanitizeBoundingBoxes
        min_size: 1
      - type: ConvertPILImage
        dtype: float32
        scale: true
      - type: ConvertBoxes
        fmt: cxcywh
        normalize: true
  shuffle: true
  num_workers: 0
  drop_last: true
  collate_fn:
    type: BatchImageCollateFunction
    scales:
    - 640
  total_batch_size: 1
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:\Users\l\Desktop\fish_dataset622\val
    ann_file: C:\Users\l\Desktop\fish_dataset622\val\coco_detection_val0.json
    return_masks: false
    transforms:
      type: Compose
      ops:
      - type: Resize
        size:
        - 640
        - 640
      - type: ConvertPILImage
        dtype: float32
        scale: true
  shuffle: false
  num_workers: 0
  drop_last: false
  collate_fn:
    type: BatchImageCollateFunction
  total_batch_size: 1
print_freq: 100
output_dir: C:\Users\l\Desktop\DEIMv2-main\comparison_outputs_detr_formal\rtdetr_r18
checkpoint_freq: 1
sync_bn: true
find_unused_parameters: false
use_amp: false
scaler:
  type: GradScaler
  enabled: true
use_ema: true
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000
epoches: 72
clip_max_norm: 0.1
optimizer:
  type: AdamW
  params:
  - params: ^(?=.*backbone)(?=.*norm|bn).*$
    weight_decay: 0.0
    lr: 1.0e-05
  - params: ^(?=.*backbone)(?!.*norm|bn).*$
    lr: 1.0e-05
  - params: ^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$
    weight_decay: 0.0
  lr: 0.0001
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.0001
lr_scheduler:
  type: MultiStepLR
  milestones:
  - 1000
  gamma: 0.1
lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 2000
model: RTDETR
criterion: RTDETRCriterion
postprocessor: RTDETRPostProcessor
use_focal_loss: true
eval_spatial_size:
- 640
- 640
RTDETR:
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RTDETRTransformer
PResNet:
  depth: 18
  variant: d
  freeze_at: -1
  return_idx:
  - 1
  - 2
  - 3
  num_stages: 4
  freeze_norm: false
  pretrained: true
HybridEncoder:
  in_channels:
  - 128
  - 256
  - 512
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  use_encoder_idx:
  - 2
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.0
  enc_act: gelu
  expansion: 0.5
  depth_mult: 1
  act: silu
  version: v1
RTDETRTransformer:
  feat_channels:
  - 256
  - 256
  - 256
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  num_levels: 3
  num_layers: 3
  num_queries: 300
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  eval_idx: -1
RTDETRPostProcessor:
  num_top_queries: 300
RTDETRCriterion:
  weight_dict:
    loss_vfl: 1
    loss_bbox: 5
    loss_giou: 2
  losses:
  - vfl
  - boxes
  alpha: 0.75
  gamma: 2.0
  matcher:
    type: HungarianMatcher
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
    alpha: 0.25
    gamma: 2.0
